dist: xenial
services:
- postgresql
matrix:
  include:
    - addons:
      postgresql: "9.4"
    - addons:
      postgresql: "9.6"
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database ecide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- cd decide
- python ./manage.py test --keepdb
notifications:
  email: false
